from fastapi import APIRouter, HTTPException, Request
from models.schemas import UltrafreeSiteCreate, EventData
from services.ultrafree import create_ultrafree, list_ultrafree, log_ultrafreeevent
from processing.ultrafree import process_analytics

router = APIRouter()

@router.post("/api/ultrafree")
async def create_ultrafree_site_endpoint(request: UltrafreeSiteCreate):
    """
    Create a new ultrafree site (public dashboard) without authentication.
    
    Request body:
        - site_name: Name of the site
        - site_url: URL of the site
        - hex_share_id: 12-character alphanumeric hex code (generated by frontend)
    
    Returns:
        The created site record with all details
    """
    try:
        site = create_ultrafree(
            site_name=request.site_name,
            site_url=request.site_url,
            hex_share_id=request.hex_share_id,
        )
        return {
            "success": True,
            "data": site,
            "message": "Site created successfully"
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/ultrafree/{hex_id}")
async def get_ultrafree_site_endpoint(hex_id: str):
    """
    Get a single ultrafree site by its hex_share_id.
    
    Path parameters:
        - hex_id: The hex share ID of the site
    
    Returns:
        The site record with all details
    """
    try:
        from services.ultrafree import get_ultrafree
        site = get_ultrafree(hex_id)
        if not site:
            raise HTTPException(status_code=404, detail="Site not found")
        return {
            "success": True,
            "data": site
        }
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/ultrafree")
async def list_ultrafree_sites_endpoint(limit: int = 20, offset: int = 0):
    """
    Get all ultrafree public sites with pagination.
    
    Query parameters:
        - limit: Number of sites to return (default: 20)
        - offset: Number of sites to skip (default: 0)
    
    Returns:
        List of all ultrafree sites ordered by creation date (newest first)
    """
    try:
        result = list_ultrafree(limit=limit, offset=offset)
        return {
            "success": True,
            "data": result["data"],
            "count": len(result["data"]),
            "total": result["total"]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.post("/api/ultrafreeevents")
async def log_event_endpoint(event: EventData, request: Request):
    """
    Log analytics events for ultrafree sites.
    """
    try:
        # Get client IP from request
        client_ip = request.client.host or "unknown"
        
        # Convert Pydantic model to dict
        event_dict = event.model_dump()
        
        # Call service function to log event
        result = log_ultrafreeevent(event_dict, client_ip)
        return {
            "success": True,
            "data": result,
            "message": "Event logged successfully"
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/api/analytics/{hex_id}")
async def get_analytics_endpoint(hex_id: str):
    """
    Get processed analytics data for a site.
    Ultrafree sites always show last 30 days of data.
    
    Path parameters:
        - hex_id: The hex share ID of the site
    
    Returns:
        Processed analytics metrics including pageviews, visitors, bounce rate, etc.
    """
    try:
        # Ultrafree analytics always shows last 30 days (720 hours)
        analytics = process_analytics(site_hex=hex_id, hours=720)
        return {
            "success": True,
            "data": analytics
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
