from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from starlette.middleware.gzip import GZipMiddleware
from contextlib import asynccontextmanager
from pydantic import BaseModel
import uvicorn

# from routers import analytics, dashboard, public, tracker
from core.config import supabase
from models.schemas import UltrafreeSiteCreate, UltrafreeSiteResponse, UltrafreeSiteList
from services.ultrafree import create_ultrafree, list_ultrafree

# Lifespan event handler
@asynccontextmanager
async def lifespan(app: FastAPI):
    # Startup - test Supabase connection
    try:
        # Test connection by querying sites table
        response = supabase.table("ultrafree").select("id").limit(1).execute()
        print("✓ Connected to Supabase")
    except Exception as e:
        print(f"⚠️  Supabase connection warning: {e}")
    yield
    # Shutdown
    pass

# Initialize FastAPI app
app = FastAPI(
    title="Web Analytics API",
    description="Analytics API for website tracking and monitoring",
    version="1.0.0",
    lifespan=lifespan
)

# Middleware stack
app.add_middleware(GZipMiddleware, minimum_size=1000)
app.add_middleware(
    TrustedHostMiddleware, 
    allowed_hosts=["localhost", "127.0.0.1", "*.vercel.app"]
)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",
        "http://localhost:3001",
        "https://*.vercel.app",
        "https://*.netlify.app"
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
# app.include_router(tracker.router, prefix="/public", tags=["tracker"])
# app.include_router(public.router, prefix="/api/public", tags=["public"])
# app.include_router(analytics.router, prefix="/api/analytics", tags=["analytics"])
# app.include_router(dashboard.router, prefix="/api/dashboard", tags=["dashboard"])

# Health check endpoint
@app.get("/health")
async def health_check():
    return {
        "status": "ok",
        "service": "web-analytics-api"
    }

# Root endpoint
@app.get("/")
async def root():
    return {
        "message": "Web Analytics API",
        "version": "1.0.0",
        "docs": "/docs"
    }


# Ultrafree Sites endpoint
@app.post("/api/ultrafree")
async def create_ultrafree_site_endpoint(request: UltrafreeSiteCreate):
    """
    Create a new ultrafree site (public dashboard) without authentication.
    
    Request body:
        - site_name: Name of the site
        - site_url: URL of the site
        - hex_share_id: 12-character alphanumeric hex code (generated by frontend)
    
    Returns:
        The created site record with all details
    """
    try:
        site = create_ultrafree(
            site_name=request.site_name,
            site_url=request.site_url,
            hex_share_id=request.hex_share_id,
        )
        return {
            "success": True,
            "data": site,
            "message": "Site created successfully"
        }
    except ValueError as e:
        raise HTTPException(status_code=400, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@app.get("/api/ultrafree")
async def list_ultrafree_sites_endpoint(limit: int = 20, offset: int = 0):
    """
    Get all ultrafree public sites with pagination.
    
    Query parameters:
        - limit: Number of sites to return (default: 20)
        - offset: Number of sites to skip (default: 0)
    
    Returns:
        List of all ultrafree sites ordered by creation date (newest first)
    """
    try:
        result = list_ultrafree(limit=limit, offset=offset)
        return {
            "success": True,
            "data": result["data"],
            "count": len(result["data"]),
            "total": result["total"]
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=True,
        log_level="info"
    )
