# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub:
    """AnalyticsService exposes the core web-analytics RPCs.
    Browser clients should reach this via a gRPC-Web / Connect gateway;
    server-to-server and Node.js clients can call it directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LogEvent = channel.unary_unary(
                '/analytics.AnalyticsService/LogEvent',
                request_serializer=analytics__pb2.LogEventRequest.SerializeToString,
                response_deserializer=analytics__pb2.LogEventResponse.FromString,
                _registered_method=True)
        self.GetSite = channel.unary_unary(
                '/analytics.AnalyticsService/GetSite',
                request_serializer=analytics__pb2.GetSiteRequest.SerializeToString,
                response_deserializer=analytics__pb2.Site.FromString,
                _registered_method=True)
        self.CreateSite = channel.unary_unary(
                '/analytics.AnalyticsService/CreateSite',
                request_serializer=analytics__pb2.CreateSiteRequest.SerializeToString,
                response_deserializer=analytics__pb2.Site.FromString,
                _registered_method=True)
        self.ListSites = channel.unary_unary(
                '/analytics.AnalyticsService/ListSites',
                request_serializer=analytics__pb2.ListSitesRequest.SerializeToString,
                response_deserializer=analytics__pb2.ListSitesResponse.FromString,
                _registered_method=True)
        self.GetAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetAnalytics',
                request_serializer=analytics__pb2.GetAnalyticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.Analytics.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/analytics.AnalyticsService/HealthCheck',
                request_serializer=analytics__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=analytics__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """AnalyticsService exposes the core web-analytics RPCs.
    Browser clients should reach this via a gRPC-Web / Connect gateway;
    server-to-server and Node.js clients can call it directly.
    """

    def LogEvent(self, request, context):
        """LogEvent ingests a single tracking event (equivalent of POST /api/ping).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSite(self, request, context):
        """GetSite fetches a public site by its 12-char hex share ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSite(self, request, context):
        """CreateSite creates a new public ultrafree site.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSites(self, request, context):
        """ListSites paginates over public sites, newest first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAnalytics(self, request, context):
        """GetAnalytics returns processed analytics for a public site.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """HealthCheck is a simple liveness probe for the gRPC server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LogEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.LogEvent,
                    request_deserializer=analytics__pb2.LogEventRequest.FromString,
                    response_serializer=analytics__pb2.LogEventResponse.SerializeToString,
            ),
            'GetSite': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSite,
                    request_deserializer=analytics__pb2.GetSiteRequest.FromString,
                    response_serializer=analytics__pb2.Site.SerializeToString,
            ),
            'CreateSite': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSite,
                    request_deserializer=analytics__pb2.CreateSiteRequest.FromString,
                    response_serializer=analytics__pb2.Site.SerializeToString,
            ),
            'ListSites': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSites,
                    request_deserializer=analytics__pb2.ListSitesRequest.FromString,
                    response_serializer=analytics__pb2.ListSitesResponse.SerializeToString,
            ),
            'GetAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalytics,
                    request_deserializer=analytics__pb2.GetAnalyticsRequest.FromString,
                    response_serializer=analytics__pb2.Analytics.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=analytics__pb2.HealthCheckRequest.FromString,
                    response_serializer=analytics__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """AnalyticsService exposes the core web-analytics RPCs.
    Browser clients should reach this via a gRPC-Web / Connect gateway;
    server-to-server and Node.js clients can call it directly.
    """

    @staticmethod
    def LogEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/LogEvent',
            analytics__pb2.LogEventRequest.SerializeToString,
            analytics__pb2.LogEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetSite',
            analytics__pb2.GetSiteRequest.SerializeToString,
            analytics__pb2.Site.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/CreateSite',
            analytics__pb2.CreateSiteRequest.SerializeToString,
            analytics__pb2.Site.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSites(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/ListSites',
            analytics__pb2.ListSitesRequest.SerializeToString,
            analytics__pb2.ListSitesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetAnalytics',
            analytics__pb2.GetAnalyticsRequest.SerializeToString,
            analytics__pb2.Analytics.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/HealthCheck',
            analytics__pb2.HealthCheckRequest.SerializeToString,
            analytics__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MutexServiceStub:
    """============================ Mutual Exclusion ============================
    Ricart-Agrawala distributed mutual exclusion. Three equal peer nodes compete
    for one shared resource with no central coordinator. Priority is decided by
    Lamport timestamps: the peer with the lowest (timestamp, node_id) goes first.

    Peer-to-peer mutual exclusion service.
    Every Artist node runs this server AND calls it on its peers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestAccess = channel.unary_unary(
                '/analytics.MutexService/RequestAccess',
                request_serializer=analytics__pb2.AccessRequest.SerializeToString,
                response_deserializer=analytics__pb2.AccessReply.FromString,
                _registered_method=True)


class MutexServiceServicer:
    """============================ Mutual Exclusion ============================
    Ricart-Agrawala distributed mutual exclusion. Three equal peer nodes compete
    for one shared resource with no central coordinator. Priority is decided by
    Lamport timestamps: the peer with the lowest (timestamp, node_id) goes first.

    Peer-to-peer mutual exclusion service.
    Every Artist node runs this server AND calls it on its peers.
    """

    def RequestAccess(self, request, context):
        """RequestAccess asks a peer for permission to enter the critical section.
        A peer either returns immediately (grant) or blocks the RPC until it is
        that peer's turn (defer) — the RPC response itself IS the reply.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MutexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestAccess': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAccess,
                    request_deserializer=analytics__pb2.AccessRequest.FromString,
                    response_serializer=analytics__pb2.AccessReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.MutexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.MutexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MutexService:
    """============================ Mutual Exclusion ============================
    Ricart-Agrawala distributed mutual exclusion. Three equal peer nodes compete
    for one shared resource with no central coordinator. Priority is decided by
    Lamport timestamps: the peer with the lowest (timestamp, node_id) goes first.

    Peer-to-peer mutual exclusion service.
    Every Artist node runs this server AND calls it on its peers.
    """

    @staticmethod
    def RequestAccess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.MutexService/RequestAccess',
            analytics__pb2.AccessRequest.SerializeToString,
            analytics__pb2.AccessReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LockServiceStub:
    """============================ Deadlock Simulation ============================
    Centralised lock manager for deadlock simulation and resolution.
    Two workers (AutoSave and FinalSubmit) compete for two shared resources
    (draft and submission) in opposite order, creating a circular-wait.
    The Lock Manager maintains a wait-for graph and optionally detects cycles
    to abort the newer requester before a real deadlock forms.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AcquireLock = channel.unary_unary(
                '/analytics.LockService/AcquireLock',
                request_serializer=analytics__pb2.LockRequest.SerializeToString,
                response_deserializer=analytics__pb2.LockReply.FromString,
                _registered_method=True)
        self.ReleaseLock = channel.unary_unary(
                '/analytics.LockService/ReleaseLock',
                request_serializer=analytics__pb2.LockRequest.SerializeToString,
                response_deserializer=analytics__pb2.LockReply.FromString,
                _registered_method=True)


class LockServiceServicer:
    """============================ Deadlock Simulation ============================
    Centralised lock manager for deadlock simulation and resolution.
    Two workers (AutoSave and FinalSubmit) compete for two shared resources
    (draft and submission) in opposite order, creating a circular-wait.
    The Lock Manager maintains a wait-for graph and optionally detects cycles
    to abort the newer requester before a real deadlock forms.

    """

    def AcquireLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AcquireLock': grpc.unary_unary_rpc_method_handler(
                    servicer.AcquireLock,
                    request_deserializer=analytics__pb2.LockRequest.FromString,
                    response_serializer=analytics__pb2.LockReply.SerializeToString,
            ),
            'ReleaseLock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLock,
                    request_deserializer=analytics__pb2.LockRequest.FromString,
                    response_serializer=analytics__pb2.LockReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.LockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.LockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LockService:
    """============================ Deadlock Simulation ============================
    Centralised lock manager for deadlock simulation and resolution.
    Two workers (AutoSave and FinalSubmit) compete for two shared resources
    (draft and submission) in opposite order, creating a circular-wait.
    The Lock Manager maintains a wait-for graph and optionally detects cycles
    to abort the newer requester before a real deadlock forms.

    """

    @staticmethod
    def AcquireLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.LockService/AcquireLock',
            analytics__pb2.LockRequest.SerializeToString,
            analytics__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.LockService/ReleaseLock',
            analytics__pb2.LockRequest.SerializeToString,
            analytics__pb2.LockReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
